Repository TheSentimentalists/SentimentalistsApp-Frontend, pull requests merged in 2020-10, with the labels that each got.

#17 Main merge
  public/manifest.json
  src/App.css
  src/App.js
  src/assets/images/Sentimentalists Logo.png
  src/components/Header.js
  src/components/Main/Header.js
  src/components/URLInput.js
Labels: frontend

#20 Url input v02 with react gauge chart
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/Results/displayResults.js
  src/components/URLInput.js
  src/components/URLInput/URLInput.js
  src/components/URLInput/URLinput.css
Labels: frontend

#42 Remove JSON parsing from URLInput function
  src/components/URLInput/URLInput.js
Labels: bug

#44 Simple loading screen
  src/App.js
  src/components/Loading/Loading.js
  src/components/URLInput/URLInput.js
Labels: enhancement

#39 Display results refactor
  package-lock.json
  package.json
  src/App.js
  src/components/Results/Credibility.js
  src/components/Results/displayResults.js
Labels: frontend

#47 Add conditional line to deploy stage
  .github/workflows/node.js.yml
Labels: bug

#52 Fix package-lock.json and package.json
  package-lock.json
  package.json
  src/App.js
Labels: bug

#49 Some display fixes
  src/components/Results/ArticleSummary.js
  src/components/Results/Credibility.js
  src/components/Results/displayResults.js
Labels: frontend

#59 add Grid item for header + style
  src/components/Results/displayResults.js
Labels: frontend
